### ISSUE TITLE
Javascript error upon trying to open the Camunda Modeler

### ISSUE THREAD

**Issue by justin-levine** [viadee/camunda-modeler-tooltip-plugin#3]
**Steps to Reproduce**
1. Download `camunda-modeler-tooltip-plugin-0.0.4.zip`
2. Unzip into folder `camunda-modeler-tooltip-plugin-0.0.4`
3. Copy `camunda-modeler-tooltip-plugin-0.0.4` folder into user's `Application Support` directory
`mv ~/Downloads/camunda-modeler-tooltip-plugin-0.0.4 /Users/justinle/Library/Application\ Support/camunda-modeler/plugins/`
4. Open Camunda Modeler

**Expected**: Opens up Camunda Modeler and the tooltip plugin works

**Actual**: 
**A JavaScript error occurred in the main process**
```
Uncaught Exception:
/Users/justinle/Library/Application Support/camunda-modeler/plugins/camunda-modeler-tooltip-plugin-0.0.4/client/index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import {
                                                                                                                                                                  ^
SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:678:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by justin-levine** [comment]
I needed to update the Camunda Modeler to `Version 4.4.0 (4.4.0.6956)`. Oops.
